---
- name: configuring VM tagging in nsx-t with ansible
  hosts: localhost
  vars:
    nsxt:
      username: '{{ lookup("env", "NSX-T_USERNAME") }}'
      password: '{{ lookup("env", "NSX-T_PASSWORD") }}'

  gather_facts: no
  tasks:
    - name: Get the tag info about VM in nsx-t network
      uri:
        url: https://10.1.22.3/api/v1/fabric/virtual-machines?display_name=web-server&included_fields=tags
        method: GET
        force_basic_auth: yes
        validate_certs: no
      register: tags_info

    - debug: 
        var: tags_info

    - name: Attach a new tag to the VM in nsx-t network
      uri:
        url: https://10.1.22.3/api/v1/fabric/virtual-machines?action=update_tags
        method: POST
        body: "{{ lookup('file','myfile.json') }}"
        force_basic_auth: yes
        body_format: json
        status_code: 204
        validate_certs: no
