---
# tasks file for apache
- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
