# install apache on redhat server
- name: installing apache package 
  shell: |
     yum install httpd -y
     systemctl enable httpd
     systemctl start httpd

- name: inserting webserver file
  copy:
    src: rhel.html
    dest: "{{ remote_dest_path }}"
    owner: root
    group: root
    mode: '777'
