---
- name: Install server role requirements on linux
  gather_facts: yes
  hosts: linux
  roles:
    - { role: Roles/apache, when: server_role == 'webserver' and server_type_name == 'apache' }
    - { role: Roles/Postgresql, when: server_role == 'sqlserver' and server_type_name == 'postgresql' }
    - { role: Roles/Mysql, when: server_role == 'sqlserver' and server_type_name == 'mysql' }
    - { role: Roles/Vsftp, when: server_role == 'fileserver' and server_type_name == 'vsftpd' }
